BlogClone/BlogClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'account/login/$', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'account/logout/$', views.LogoutView.as_view(), name='logout', kwargs={'next_page':'/'}),
]

BlogClone/blog/urls.py
from django.conf.urls import url
from blog import views

app_name = 'blog'
urlpatterns=[
    url(r'^$', views.PostListView.as_view(template_name = 'blog/post_list.html'), name='post_list'),
    url(r'about/$', views.About.as_view(), name='about'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(template_name = 'blog/post_detail.html'), name='post_detail'),
    url(r'^post/new/$', views.PostCreateView.as_view(),name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^draft/$', views.DraftView.as_view(template_name = 'blog/post_draft_list.html'), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish$', views.post_publish, name='post_publish'),

]

BlogClone/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

# this class will contain all the information about the post
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE) #Builtin User table's userid is fk to Post Table
    title = models.CharField(max_length = 256)
    content = models.TextField()
    created_date = models.DateField(default = timezone.now)
    published_date = models.DateField(blank=True, null=True)

    #Here some functions would be there that would help handling db

    #will publish post DateField
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    #will get a list of all approved comments
    def approve_comments(self):
        return self.comments.filter(is_approved=True)

    def __str__(self):
        return self.title

    #tells the post request what to do after a clicking btn
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk':self.pk})


#this class is of all comments done on every Post
class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments',on_delete=models.CASCADE) #Postid(builtin by django) is fk to Comment table
    author = models.CharField(max_length=256)
    content = models.TextField()
    created_date = models.DateField(default=timezone.now())
    is_approved = models.BooleanField(default=False)

    #Here some functions would be there that would help handling db
    #will change the element is_approved from false to true
    def approve(self):
        self.is_approved = True
        self.save()

    def __str__(self):
        return self.author

    #tells the post request what to do after a clicking btn
    def get_absolute_url(self):
        return reverse('blog:post_list', kwargs={'pk':self.pk})

BlogClone/blog/forms.py
from django import forms
from blog.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author', 'title', 'content')
        #helps you style the form using connection to css
        widgets={
            #textinputclass and postcontent are the class we will make in css rest all the class is builtin to css
            'title': forms.TextInput(attrs={'class':'textinputclass'}),
            'content':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent', 'id':'editor1'})
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author', 'content')
        #helps you style the form using connection to css
        widgets={
            #textinputclass are the class we will make in css rest all the class is builtin to css
            'author': forms.TextInput(attrs={'class':'textinputclass'}),
            'content':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

BlogClone/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (TemplateView, ListView, DetailView, CreateView,
                                    UpdateView, DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm
from django.utils import timezone
# Create your views here.
##################################################################################
#POST VIEWS!!!#
#About page
class About(TemplateView):
    template_name = 'blog/about.html'

#displaying the list of post on home page so in urls.py(project) will be mapped as home page
class PostListView(ListView):
    model = Post
    context_object_name='post_list'
     #to show only those post that has been published(i.e. published_date is !null)
    def get_queryset(self):
         #this is a sql query like linq in .net
         return Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
                #select * from Post where published_date <= NOW() orderby published_date

#displaying details of particular post
class PostDetailView(DetailView):
     model = Post

#create the post but grant access to those only those are the user(here superuser)
#LoginRequiredMixin acts same as the decorators, it checks wether loggedin or not
class PostCreateView(LoginRequiredMixin,CreateView):
     login_url='/login/'#Default return value for function get_login_url()
     #get_login_url()
     #Returns the URL that users who don’t pass the test(are not loggedin)
     # will be redirected to. Returns login_url if set, or settings.LOGIN_URL otherwise.

     redirect_field_name = 'blog/post_detail.html'#Default return value for function get_redirect_field_name().
     #get_redirect_field_name()
     #Returns the name of the query parameter that will contain the URL
     #the user should be redirected to after a successful login

     form_class = PostForm #connects forms.py to model.py
     model = Post

#update the post i.e. lets you edit the post
#same as create, only user(here superuser) can edit the post
class PostUpdateView(LoginRequiredMixin, UpdateView):
     login_url = '/login/'
     redirect_field_name = 'blog/post_detail.html'
     form_class = PostForm #connects forms.py to model.py
     model = Post

#Deletes the form
#same as create, only user(here superuser) can edit the post
class PostDeleteView(LoginRequiredMixin,DeleteView):

    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    model = Post
    success_url = reverse_lazy('blog:post_list')

#display list of posts which are draft i.e. dont have any published_date
class DraftView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post
    context_object_name = 'posts'
    #sql query where published_date is null
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

#function for publishing the posts
#but to publish we need to be loggedin, hence for function we use decorators
@login_required
def post_publish(request, pk):
     post = get_object_or_404(Post, pk=pk) #creates object post with particular pk
     post.publish()
     return redirect('blog:post_detail',pk=pk) #have to specify the pk as in url it require it as parameter


######################################################################################################
#COMMENT VIEWS!!!!!#

#funtion for comment form which add comments to the post
#for that user need to be loggedin
@login_required
def add_comment_to_post(request, pk):
     post = get_object_or_404(Post, pk=pk)
     if request.method == 'POST':
         form = CommentForm(request.POST)
         if form.is_valid():
             comment = form.save(commit=False)
             comment.post = post #Comment model there is a post which is a fk,
             #this statement is assigning this->post object to the table->post and hence filling all entities in Table
             comment.save()
             return redirect('blog:post_detail', pk=post.pk)
     else:#ie a get request
        form=CommentForm()
        return render(request,'blog/comment_form.html', {'form':form})

#function for approving the comment, hence loggedin require
@login_required
def comment_approve(request,pk):
     comment = get_object_or_404(Comment, pk=pk)
     comment.approve() #Comment model we created the method approve
     return redirect('blog:post_detail', pk=comment.post.pk)

#funtion for deletion
@login_required
def comment_remove(request, pk):
     comment = get_object_or_404(Comment, pk=pk)
     post_pk = comment.post.pk
     comment.delete() #just like .save(), delete() method is builtin to django
     return redirect('blog:post_draft_list')

BlogClone/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
<h1>About Company</h1>
<h3>Thanks for checking</h3>
{% endblock %}

BlogClone/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <!--bootstrap link css-->
      <script src="C:/Anaconda/DjangoProjects/BlogClone/ckeditor.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">  
    <!--wordpad style editor link-->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!--our css link-->
    <link rel="stylesheet" href="{%static 'css/blog.css'%}">
    <!--Google fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-default techfonts custom-navbar">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My Blog</a></li>
          <li><a class="navbar-link" href="{% url 'blog:about' %}">About</a></li>
          <li><a class="navbar-link" href="https://www.github.com">GitHub</a></li>
          <li><a class="navbar-link" href="https://www.linkedin.com">LinkedIn</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <!--user.is_authenticated is a built in funtion, which tells wether user is loggedin or not-->
          {% if user.is_authenticated %}
          <li><a href="{% url 'blog:post_new' %}">Create</a></li>
          <li><a href="{% url 'blog:post_draft_list' %}">Drafts</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          <li><a >Welcome: {{ user.username }}</a></li>
          {% else %}
          <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog_post">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

BlogClone/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% block content %}
<h1>New Comment</h1>
<form class="loader"  method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Post</button>
</form>
<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

BlogClone/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
<form  method="POST">
  {% csrf_token %}
  <p>Are you sure wanna delete?</p>
  <input type="submit" class="btn btn-primary" value="Submit">
</form>
{% endblock %}

BlogClone/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<h1 class="loader">{{ post.title }}</h1>
<hr>
  {% if post.published_date %}
    <div class="date postdate">
      {{post.published_date}}
    </div>
    <hr>
  {% else %}
  <a class="btn btn-pimary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a><hr>
  {% endif %}
  <p class="postcontent">{{ post.content|safe|linebreaks }}</p>
  <hr>
  {% if user.is_authenticated %}
  <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
  <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
  {% endif %}
  <hr>
  <a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>
  <div class="container">
    {% for comment in post.comments.all %}
      <br>
      {% if user.is_authenticated or comment.is_approved %}

        {% if not comment.is_approved %}
        <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
        <a class="btn btn-primary" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <p>  {{comment.created_date}}</p>
        <p>{{ comment.content|safe|linebreaks }}</p>
        <p>Posted by: {{ comment.author }}</p>
        <hr>
      {% endif %}
      {% empty %}
      <p>No Commets</p>
    {% endfor %}
  </div>
{% endblock %}

BlogClone/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}
{% block content %}
 {% for post in posts %}
 <div class="post loader">
   <p class="date">created: {{post.created_date}}</p>
   <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
   <p>{{post.content}}</p>
 </div>
 {% endfor %}
{% endblock %}

BlogClone/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
<h1>New Post</h1>
<form class="post-form loader"  method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Save</button>
</form>

<script >
  CKEDITOR.replace( 'editor1' );
</script>
{% endblock %}

BlogClone/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
<div class="centerstage">
    {% for post in post_list %}
    <div class="post loader">
      <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
      <div class="date">
        <p>Published on: {{post.published_date}}</p>
      </div>
      <a href="{% url 'blog:post_detail' pk=post.pk %}">Comment:{{ post.approve_comments.count }}</a>
    </div>
    {% endfor %}
</div>
{% endblock %}